from os import environ
from os.path import join

INPUT_FOLDER_PATH = "./input"
OUTPUT_FOLDER_PATH = "./output/"


WHISPER_MODEL = "medium"
WHISPER_RESULT_TEXT_KEY = "text"


YOUTUBE_VIDEO_URL_TEMPLATE = "https://www.youtube.com/watch?v={}"
DATASET_FILENAME = "dataset.json"
DATASET_FILE_PATH = join(OUTPUT_FOLDER_PATH, DATASET_FILENAME)

DOCUMENT_SOURCE = "file"


RETRIEVAL_PLUGIN_PROTOCOL = "http"
RETRIEVAL_PLUGIN_SCHEMA = f"{RETRIEVAL_PLUGIN_PROTOCOL}://"
RETRIEVAL_PLUGIN_HOSTNAME = environ["RETRIEVAL_PLUGIN_HOSTNAME"]
RETRIEVAL_PLUGIN_PORT = "8000"
RETRIEVAL_PLUGIN_HOST = (
    f"{RETRIEVAL_PLUGIN_SCHEMA}{RETRIEVAL_PLUGIN_HOSTNAME}:{RETRIEVAL_PLUGIN_PORT}"
)
RETRIEVAL_PLUGIN_UPSERT_ENDPOINT = f"{RETRIEVAL_PLUGIN_HOST}/upsert"
RETRIEVAL_PLUGIN_BEARER_TOKEN = environ["RETRIEVAL_PLUGIN_BEARER_TOKEN"]
RETRIEVAL_PLUGIN_UPSERT_CHUNK_SIZE = 2
RETRIEVAL_PLUGIN_UPSERT_DOCUMENTS_KEY = "documents"
RETRIEVAL_PLUGIN_RETRIES = 5
RETRIEVAL_PLUGIN_RETRY_BACKOFF_FACTOR = 0.1


AUTHORIZATION_HEADER_NAME = "Authorization"
AUTHORIZATION_TYPE_BEARER = "Bearer"


class DocumentField:
    ID = "id"
    TEXT = "text"
    METADATA = "metadata"

    class Metadata:
        URL = "url"
        SOURCE = "source"
